### ISSUE TITLE
NPM Warnings when npm install (No description, No repository field, No README data & No license field)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#113]
When I install the node.js dependencies on `localhost` I get the following set of npm warnings:
![image](https://user-images.githubusercontent.com/194400/37878658-563609a0-3064-11e8-8316-c61dd29f948c.png)

The [`package.json`](https://github.com/dwyl/github-backup/blob/9aec5c46b47922ea0cfd4c486008d0fb44b1248a/assets/package.json#L1-L19) file _currently_ looks like this:
https://github.com/dwyl/github-backup/blob/9aec5c46b47922ea0cfd4c486008d0fb44b1248a/assets/package.json#L1-L19

## Todo

+ [ ] Add No description
+ [ ] Add repository field.
+ [ ] Add README data
+ [ ] Add license field.

borrow the definitions (_with a find-and-replace_) from:
https://github.com/dwyl/hapi-auth-jwt2/blob/master/package.json
