### ISSUE TITLE
😕

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#135]
https://www.zdnet.com/article/a-hacker-is-wiping-git-repositories-and-asking-for-a-ransom 
![image](https://user-images.githubusercontent.com/194400/57178363-baba4580-6e66-11e9-91bc-e32b446f8ea1.png)

# Todo

+ [ ] Revive this project 
+ [ ] Backup all our repos
  + [ ] code
  + [ ] issues
+ [ ] schedule a Git Hook that performs the backup on each commit or issue/PR update
+ [ ] document it so others can use it

**Comment by nelsonic** [comment]
![github-down-again](https://user-images.githubusercontent.com/194400/170717121-76d049d2-fe36-4697-9bc3-f9322ec83b77.png)
