### ISSUE TITLE
Epic: "Meta Data Table" in Issue Description

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#14]
As a `user` of the GitHub Backup App,
`I want` to see at a _glance_ if an issue has "version history"
`so that` I know there is "history" and I can click to see it!

## Acceptance Criteria

+ [ ] **Meta Table** should be inserted into the **issue description** when the issue is Created.
  + [ ] an  comment advising people _not_ to delete/change it. 
  e.g: `<!-- avoid editing below this line to preserve issue history -->` (_see below_)

+ [ ] Minimise space occupied by the table to **Two Rows** to avoid clutter: 
Heading (Key) & Row-Cell (Value) >> see below for example.

+ [ ] Display the revision count for the issue.
We already have a "Proof of Concept" for using SVG as a Counter: http://hits.dwyl.io 
e.g: [![HitCount](http://hits.dwyl.io/dwyl/github-backup.svg)](http://hits.dwyl.io/dwyl/github-backup)

+ [ ] Display a "**short link**" (_dependent on the App / Domain Name chosen. see:_ #13)

## Optional (_Nice-to-Have_)
+ [ ] Subtle Color/Branding in the table.

## Question / Discussion:

What _other_ info would it be _useful_ to display in the "**Meta Table**"?
(_or should we "**keep** it **simple** for **MVP** and ask **users** once deployed_...?)

## Example:

Issue Edit Count | View History
:---------:|---------
9     | [gibu.io/**dwhq321**](https://github.com/dwyl/github-backup/issues/13)

**Comment by SimonLab** [comment]
> What other info would it be useful to display in the "Meta Table"?
I think the example (number of time the issue has been edited and link to the history view) is a good start for an MVP! If this table works it will be easy to add more info but more complicated to remove existing data (maybe not too much technically but from the user experience it might feels strange)
 
Is the meta table represents any edits (on the issue description and on the comments of the issue)? If yes I think it makes sense to only display the meta table on the description issue. We might need to find a way to explain this on the meta table (ie. "Issue/Comments Edit Cout" :thinking: ) as it might not be obvious at a first sight.

**Comment by nelsonic** [comment]
@SimonLab _good_ question. I feel that we should ***test*** this. 
(_i.e. Meta Table in _first_ comment vs. any comment with edits ..._)

_Most_ comments _don't_ have edits so it won't be _too_ bad if we have the Meta Table in any comment that has an edit.
My "fear" is that we add a table to a _one-line_ comment where someone fixed a typo.
It would "_clutter_" the comment ... 🤔 

For _now_ (MVP) let's only insert the Meta Table in the _first_ comment and then get User-Feedback on the Feature ...

**Comment by SimonLab** [comment]
Thanks for the clarification @nelsonic and agree let's focus on the edit history of the issue description instead of the comments at least for the MVP.

The only other information I would add on the meta table is a link/logo to the github app on the marktplace so that users can install the app easily via the meta table

**Comment by nelsonic** [comment]
@SimonLab on the subject of having a link/logo in the Meta Table,
_initially_ I would _prefer_ to "limit self promotion" in the Issue description/comment(s)
as it does not add any _value_ to the UX ... 🤔 
Can we open an issue to discuss this separately? 
(_we might **need** this promo in order to reach the **250** downloads #17 ..._)
The fact that the "_short link_" will have our "brand" in it should be good "promo" _for now_ ...

**Comment by Cleop** [comment]
@nelsonic - what priority do you think this should be? Perhaps 2 or 3?

**Comment by nelsonic** [comment]
As soon as we are _tracking_ the history of an repo's issues we want to make that clear.
(_hence `priority-2`..._) 👍

**Comment by Cleop** [comment]
@nelsonic @SimonLab - if we only display the table in top comment then where would clicking on the link take you? At the moment we're organising history pages by each comment _not_ by issue. So on that basis I would start with having one per comment (where edits exist).

I also agree, the smaller the table, the better.

**Comment by nelsonic** [comment]
@Cleop the history page should be for the issue. 
and _inside_ that page should have "anchor" links to the comments 
and their respective version history. 
it should be _one_ page regardless of how many comments and versions.
unless it takes "_ages_" to load (_which we can "**optimise later**"_).
