### ISSUE TITLE
Epic: Define (Ecto) PostgreSQL Database Schema

### ISSUE THREAD

**Issue by nelsonic** [dwyl/github-backup#15]
All the "Meta Data" (_anything that is not an issue comment, which is Markdown/"Rich Text"_)
of issues will be stored in a PostgreSQL Database.

With reference to the GitHub API for `users`, `issues` and `comments`,
we need to create the Ecto (Database) Schema for the three DB tables.
We are going to "normalise" the data and let Ecto construct the queries.

+ [ ] Users: https://developer.github.com/v3/users 
+ [ ] Issues: https://developer.github.com/v3/issues 
+ [ ] Comments: https://developer.github.com/v3/issues/comments 

Our aim is to match the _field names_ in the GitHub API _exactly_ 
so we keep an _exact_ copy the data that people can _easily_ download 
if they want to have a Local Copy. (_don't worry, we aren't building the download feature **yet**!_)

**Comment by Cleop** [comment]
In the long run we might want these two tables to help us display our UI better but for now if people are accessing their comments directly from the issue then they wouldn't be necessary. 
| Organisations |
|---------------|
| ID       |
| Organisation name |

| Repositories |
|--------------|
| ID      |
| Repo name    |

Do people think we should include them in our schema now or add them later if necessary?

**Comment by nelsonic** [comment]
@Cleop if we _know_ the desired schema _up-front_ then we should create it as close to the "long term" as possible.

**Comment by Cleop** [comment]
Do we need the avatar url in our schema for displaying the user's photo next to their comments?
![image](https://user-images.githubusercontent.com/16775804/36787703-f0d4d806-1c82-11e8-8904-99c254b49ed6.png)

**Comment by nelsonic** [comment]
@Cleop yeah, we _should_ save the `"avatar_url"`.
For now please _assume_ we are storing ***all*** the info for a user. 
Thanks.

**Comment by Cleop** [comment]
Still to do #46
