### ISSUE TITLE
MVP Project setup

### ISSUE THREAD

**Issue by SimonLab** [dwyl/github-backup#18]
As a developer of the MVP
I want to define an easy setup of the application
So that I can start implementing, deploying and validating the main ideas of github-backup

- [x] Create a Github App #7 & #19 
- [x] Create Phoenix server #12 & #20 
- [x] Create Heroku app #16

Once these three main steps are done we can
- [x] Add a Postgres database on Heroku
- [x] Create a storage space (S3?) to store history of issues edit 

@nelsonic @iteles If this setup sounds good to you, do you have a preference on how to create the Heroku app: should I create a new account with a gmail address or should we create the app on a dwyl account?

**Comment by Cleop** [comment]
Steps for setting up Amazon S3 (Simple Storage Service). Assumption: you already have an AWS account.

- Create a bucket for your project (think of a bucket like a folder). 

Every bucket is assigned to a region, you can choose any AWS Region that is geographically close to you for optimisation of cost/speed. You are not charged for creating a bucket. You are only charged for storing objects in the bucket and for transferring objects out of the bucket. Note: bucket names must be globally unique and cannot be changed, they will also feature in the url of the item so consider this when creating them.

![image](https://user-images.githubusercontent.com/16775804/36477610-c0438fea-16f9-11e8-88fc-52a7a670c210.png)
![image](https://user-images.githubusercontent.com/16775804/36477621-cc1f7428-16f9-11e8-9ac7-50b2dba3d27c.png)

**Versioning** – **Versioning enables you to keep multiple versions of an object in one bucket. Versioning is disabled for a new bucket by default.**--- relevant for this project @SimonLab ?

**Server access logging** – Server access logging provides detailed records for the requests that are made to your bucket. By default, Amazon S3 does not collect server access logs.

**Tags** – With AWS cost allocation, you can use tags to annotate billing for your use of a bucket. A tag is a key-value pair that represents a label that you assign to a bucket. To add tags, choose Tags, and then choose Add tag. 

**Object-level logging** – Object-level logging records object-level API activity by using CloudTrail data events.

**Default encryption** – Amazon S3 default encryption provides a way to set the default encryption behavior for an S3 bucket. You can set default encryption on a bucket so that all objects are encrypted when they are stored in the bucket.

**Comment by Cleop** [comment]
Next we need our files to automatically be added to S3 from our application using the S3 API.

https://devcenter.heroku.com/articles/s3

**Comment by nelsonic** [comment]
@Cleop you _`should`_ be able to access your security keys on AWS, please share your screen tomorrow morning during standup so we can debug this.

@SimonLab I _think_ the app should be "owned" by dwyl and You and Cleo should be added to the dwyl Heroku group. (_yes this means there's no "free web dynos", but that's "OK", we need to **ship**!_)

**Comment by Cleop** [comment]
Having added the config vars to heroku, next comes deciding how files will be uploaded to S3. The 2 options are: direct uploads or pass-through uploads.

**Comment by nelsonic** [comment]
@Cleop _users_ are not uploading anything to S3.
Our Phoenix App will create a `{commentid}.md` file in the S3 bucket using [`ex-aws`](https://github.com/ex-aws/ex_aws) and store a _reference_ to it in the `comment_history` table.
We _really_ need a _separate_ issue for "Saving Comment Richtext Data to S3" as this isn't really "_setup_" it's "_technical **implementation detail**_" ...

**Comment by Cleop** [comment]
Having created #31 for the saving of data to S3, I've ticked the checkbox on this issue for setting up my account and creating a bucket.

**Comment by Cleop** [comment]
Closing as 'Done' in the Projects board.
